// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// const SUPABASE_URL = "https://abmgefjajmeqozszwdfr.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibWdlZmpham1lcW96c3p3ZGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDQ5NTAsImV4cCI6MjA2NTk4MDk1MH0.31oIPslRCAaOl6_IVgM6Px3haf_8EJR4U54mX7sWsVE";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY!;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
